### PR TITLE
Add patch to fix glew for MSVS 2019

### LINKED ISSUE #59: Building SDK with MSVC 2019
I installed MSVC 2019 and tried to build the SDK. I ran into issues:

1) GLEW 2.1.0 fails to link, as discussed here https://github.com/nigels-com/glew/issues/238#issuecomment-543442437 and possibly fixed by this: https://github.com/nigels-com/glew/commit/4bbe8aa2ab70a6eb847ee5751735422d0ba623cd but I don't know how to apply that when building the SDK. Editing the GLEW CMakeLists.txt after the build failed once and re-starting it doesn't restart the build.

2) I had to modify the build command slightly to specify the Win32 target: `C:\Users\Geoff\Desktop\freeorion-sdk\build>cmake .. -G "Visual Studio 16 2019" -A Win32`

### PR DESCRIPTION
**Pull request by o01eg**
Fixes #59 

I hope it isn't mandatory to release new SDK.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
I don't know how to test an SDK pull request. At least hard-coding the GLEW source URL to the latest snapshot appears to fix that issue.

> I hope it isn't mandatory to release new SDK.

Not sure what you mean by that.

**Comment by o01eg** [comment]
> I don't know how to test an SDK pull request.

I suppose you could revert source changes and download `patches/glew/0003-Visual-Studio-16-release-mode-cmake-fixup.patch` file.

> Not sure what you mean by that.

It is need to fix MSVS 2019 compatibility before SDK release?

**Comment by geoffthemedio** [comment]
> I suppose you could revert source changes and download `patches/glew/0003-Visual-Studio-16-release-mode-cmake-fixup.patch` file.

Then I'd have a .patch file and no idea what to do with it...

> It is need to fix MSVS 2019 compatibility before SDK release?

If we're doing an SDK release, it would probably be a good idea to make it work with the latest compiler release.

**Comment by o01eg** [comment]
I've added test for MSVS 2019 to Appveyor CI.

**Comment by o01eg** [comment]
> Then I'd have a .patch file and no idea what to do with it...

Cmake project automatically applies it when building SDK.

**Comment by geoffthemedio** [comment]
Put the patch in patches/glew

Started SDK builds with 2017 and 2019/x64

**Comment by geoffthemedio** [comment]
With the patch, the 2017 build failed:
````
"C:\Users\Geoff\Desktop\freeorion-sdk\build_2017_32\ALL_BUILD.vcxproj" (default
 target) (1) ->
"C:\Users\Geoff\Desktop\freeorion-sdk\build_2017_32\glew.vcxproj" (default targ
et) (13) ->
(CustomBuild target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC
\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited
with code 3. [C:\Users\Geoff\Desktop\freeorion-sdk\build_2017_32\glew.vcxproj]
````

**Comment by o01eg** [comment]
@geoffthemedio Are there error above?

**Comment by geoffthemedio** [comment]
probably, but it was cut off by the console buffer limit... need to restart it...

**Comment by geoffthemedio** [comment]
The 2019/64 build didn't show an error that I saw, but ended without generating the zip, with:
````
    SDL2.vcxproj -> C:\Users\Geoff\Desktop\freeorion-sdk\build_2019_64\sdl-pref
  ix\src\sdl-build\RelWithDebInfo\SDL2.dll
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsof
t\VC\v160\Microsoft.CppCommon.targets(231,5): warning MSB8065: Custom build for
 item "C:\Users\Geoff\Desktop\freeorion-sdk\build_2019_64\sdl-prefix\src\sdl-bu
ild\CMakeFiles\66a2974c9c7e4ead197783fe35d7f29c\INSTALL_force.rule" succeeded,
but specified output "c:\users\geoff\desktop\freeorion-sdk\build_2019_64\sdl-pr
efix\src\sdl-build\cmakefiles\install_force" has not been created. This may cau
se incremental build to work incorrectly. [C:\Users\Geoff\Desktop\freeorion-sdk
\build_2019_64\sdl-prefix\src\sdl-build\install.vcxproj] [C:\Users\Geoff\Deskto
p\freeorion-sdk\build_2019_64\sdl.vcxproj]
    -- Install configuration: "RelWithDebInfo"
  Completed 'sdl'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsof
t\VC\v160\Microsoft.CppCommon.targets(231,5): warning MSB8065: Custom build for
 item "C:\Users\Geoff\Desktop\freeorion-sdk\build_2019_64\CMakeFiles\fd5876671f
1ca5b0ecf8d67101b50268\sdl.rule" succeeded, but specified output "c:\users\geof
f\desktop\freeorion-sdk\build_2019_64\cmakefiles\sdl" has not been created. Thi
s may cause incremental build to work incorrectly. [C:\Users\Geoff\Desktop\free
orion-sdk\build_2019_64\sdl.vcxproj]
````

**Comment by geoffthemedio** [comment]
Here's the full SDK build log for MSVC 2017 Win32
[build_log.zip](https://github.com/freeorion/freeorion-sdk/files/4270415/build_log.zip)

The MSVC 2019 GLEW patch was in the /patches directory for this build.

**Comment by o01eg** [comment]
Looks like patch is broken, but CI applies it without issues.

**Comment by o01eg** [comment]
Could you check which line-ending it have compared to other GLEW patches? I remember git has an option to convert it on checkout.

**Comment by o01eg** [comment]
@geoffthemedio CI passed checks. Can it be merged?

**Comment by geoffthemedio** [comment]
> Could you check which line-ending it have compared to other GLEW patches?

````
0001-CMake-Don-t-install-pkg-config-files-on-Windows.patch
0002-Don-t-install-glew-CMake-export-targets.patch
0003-Visual-Studio-16-release-mode-cmake-fixup.patch
````

**Comment by o01eg** [comment]
@geoffthemedio  Which line-ending have each file?

**Comment by geoffthemedio** [comment]
I'll try again with it merged...

**Comment by geoffthemedio** [comment]
The 2019 Win32 and 2019 x86 SDKs both built seemingly OK.

**Pull request merged**
