### PR TITLE
Add support for 64bit.

### PR DESCRIPTION
**Pull request by o01eg**

### CODE REVIEW

**Comment by adrianbroher** [comment]
There are no intermediate plans to support 64 bit in general, as there are still some issues on Mac with libpng (and possible even more ones):

https://travis-ci.org/freeorion/freeorion-sdk/builds/174188643

**Comment by Vezzra** [comment]
So, close this or leave it open...?

**Comment by o01eg** [comment]
Is issue with libpng same with new version?

**Comment by adrianbroher** [comment]
> Is issue with libpng same with new version?
Yeah, the issue still exists:

https://travis-ci.org/freeorion/freeorion-sdk/builds/191041228#L3464

**Comment by memem359** [comment]
As far as I can tell, the problem is not with libpng, but that the FO cmake scripts aren't handling multiple (MacOS) architectures correctly.

If I edit the CMakeLists.txt file, so that CMAKE_OSX_ARCHITECTURES is x86_64 instead of i386, I can build the SDK without any fatal errors.

I looked at the branch "fix-osx-universal-binary". If I put in that change (both i386 and x86_64 architectures), then I get problems in both python and libpng.

- For python, the generated pyconfig.h file has bad settings. It tries to define clock_t and size_t with values that cause compiler errors. (The Travis build failed before it got to the particular python compile.)

- For libpng, I get `clang: error: no such file or directory: 'x86_64'`
This is due to `genout.cmake`. Instead of the PLATFORM_C_FLAGS being "-arch i386 -arch x86_64", the script parses it as "-arch i386 x86_64". That is the reason for the missing x86_64 file/directory message.

**Comment by adrianbroher** [comment]
This PR was superceded by #29.

**Pull request closed without merging**
