### PR TITLE
Update boost to 1.80.0

### PR DESCRIPTION
**Pull request by o01eg**

### CODE REVIEW

**Comment by geoffthemedio** [comment]
I'm reluctant to bump Boost before the next release

**Comment by o01eg** [comment]
@geoffthemedio At least to test if it fix compilation in https://github.com/freeorion/freeorion/pull/4133

**Review by Vezzra — COMMENTED** [review]
I can build the SDK, but building FO with that SDK fails on my system, apparently due to my system being macOS 10.14, and stuff in boost 1.80 which require at least macOS 10.15.

I get a lot of build errors similar to this:
```
In file included from /Users/user/SoftwareProjekte/FO/main/src/GG/src/GUI.cpp:21:
In file included from /Users/user/SoftwareProjekte/FO/main/build/dep/include/boost/gil/extension/io/png.hpp:12:
In file included from /Users/user/SoftwareProjekte/FO/main/build/dep/include/boost/gil/extension/io/png/write.hpp:15:
/Users/user/SoftwareProjekte/FO/main/build/dep/include/boost/gil/io/make_dynamic_image_writer.hpp:64:52: error: 'path' is unavailable: introduced in macOS 10.15
auto make_dynamic_image_writer(detail::filesystem::path const& path, image_write_info<FormatTag> const& info)
```
So I guess switching to boost 1.80 will raise the minimum macOS version required to build FO to 10.15.

Although I plan to upgrade my system within the next two weeks, I'm not sure if we should do the update to boost 1.80 before 0.5 (like @geoffthemedio said).

I defer this decision to @geoffthemedio.

**Comment by o01eg** [comment]
@Vezzra It didn't fix `_copysign` issue so I won't push for update either.

**Comment by Vezzra** [comment]
Ok

**Comment by geoffthemedio** [comment]
@o01eg could try bumping to Boost 1.81 instead?

**Comment by o01eg** [comment]
@geoffthemedio Yes, I could try.

**Comment by geoffthemedio** [comment]
> Although I plan to upgrade my system within the next two weeks

@Vezzra did that upgrade happen? could we bump the minimum supported MacOS version?

**Comment by Vezzra** [comment]
> @Vezzra did that upgrade happen? could we bump the minimum supported MacOS version?

Yes. I'm now on macOS 12.6 Monterey.

**Pull request closed without merging**
