### PR TITLE
Bump python 3.7.12

### PR DESCRIPTION
**Pull request by o01eg**
Follows up #100

### CODE REVIEW

**Review by Vezzra — APPROVED** [review]
Successfully builds on macOS.

**Comment by geoffthemedio** [comment]
Fails for me...
[sdk_build.log](https://github.com/freeorion/freeorion-sdk/files/8739837/sdk_build.log)

**Comment by o01eg** [comment]
@geoffthemedio Somehow it downloads CMake scripts from   
```
-- Using src='https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/archive/bb45aa7a4cfc7a5a93bc490c6158f702d1a2226f.zip'
```

**Comment by o01eg** [comment]
Either it shouldn't be Py_BUILD_CORE defined

```c
#ifdef Py_BUILD_CORE
#  define _PyThreadState_Current _PyRuntime.gilstate.tstate_current
#  define PyThreadState_GET() \
             ((PyThreadState*)_Py_atomic_load_relaxed(&_PyThreadState_Current))
#else
#  define PyThreadState_GET() PyThreadState_Get()
#endif
```

Or _PyRuntime should be defined

**Comment by o01eg** [comment]
Also it differs from 3.6

```
#ifdef Py_BUILD_CORE
PyAPI_DATA(_Py_atomic_address) _PyThreadState_Current;
#  define PyThreadState_GET() \
             ((PyThreadState*)_Py_atomic_load_relaxed(&_PyThreadState_Current))
#else
#  define PyThreadState_GET() PyThreadState_Get()
#endif
```

**Comment by o01eg** [comment]
@geoffthemedio CI gets error

```
2022-05-20T18:33:34.2874975Z C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v150\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code -1073741701. [D:\a\freeorion-sdk\freeorion-sdk\build\python3-prefix\src\python3-build\CMakeBuild\libpython\libpython-shared.vcxproj] [D:\a\freeorion-sdk\freeorion-sdk\build\python3.vcxproj]
```

It looks like it successfully build but cannot run some program because it requires some DLL. Could you test it on Windows to such which DLL is missing or even where PATH should be set?

**Comment by geoffthemedio** [comment]
I get some `error MSB8066: Custom build for [...] exited with code 1. ` errors building the SDK:
```
       Creating library C:/Users/g_top/Desktop/sdktest/python_bump/buildpython37/python3-prefix/src/python3-build/CMakeBuild/libpython/RelWithDebInfo/_freeze_importlib.lib and object C:/Users/g_top/Desktop/sdktest/python_bump/buildpython37/python3-prefix/src/python3-build/CMakeBuild/libpython/RelWithDebInfo/_freeze_importlib.exp
    _freeze_importlib.vcxproj -> C:\Users\g_top\Desktop\sdktest\python_bump\buildpython37\python3-prefix\src\python3-build\CMakeBuild\libpython\RelWithDebInfo\_freeze_importlib.exe
    Generating C:/Users/g_top/Desktop/sdktest/python_bump/buildpython37/python3-prefix/src/python3/Python/importlib_external.h, C:/Users/g_top/Desktop/sdktest/python_bump/buildpython37/python3-prefix/src/python3/Python/importlib.h
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'C:\Users\g_top\Desktop\sdktest\python_bump\buildpython37\python3-prefix\src\python3-build\CMakeFiles\a96301076183e852ffaf2721ca6949ed\importlib_external.h.rule' exited with code -1073741701. [C:\Users\g_top\Desktop\sdktest\python_bump\buildpython37\python3-prefix\src\python3-build\CMakeBuild\libpython\libpython-shared.vcxproj] [C:\Users\g_top\Desktop\sdktest\python_bump\buildpython37\python3.vcxproj]
````
````
    Generating Code...
       Creating library C:/Users/g_top/Desktop/sdktest/python_bump/buildpython37/python3-prefix/src/python3-build/CMakeBuild/libpython/RelWithDebInfo/pgen.lib and object C:/Users/g_top/Desktop/sdktest/python_bump/buildpython37/python3-prefix/src/python3-build/CMakeBuild/libpython/RelWithDebInfo/pgen.exp
    pgen.vcxproj -> C:\Users\g_top\Desktop\sdktest\python_bump\buildpython37\python3-prefix\src\python3-build\CMakeBuild\libpython\RelWithDebInfo\pgen.exe
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'C:\Users\g_top\Desktop\sdktest\python_bump\buildpython37\CMakeFiles\91fb0f334500d963f7f6f7b34afecfa7\python3-mkdir.rule;C:\Users\g_top\Desktop\sdktest\python_bump\buildpython37\CMakeFiles\91fb0f334500d963f7f6f7b34afecfa7\python3-download.rule;C:\Users\g_top\Desktop\sdktest\python_bump\buildpython37\CMakeFiles\91fb0f334500d963f7f6f7b34afecfa7\python3-update.rule;C:\Users\g_top\Desktop\sdktest\python_bump\buildpython37\CMakeFiles\91fb0f334500d963f7f6f7b34afecfa7\python3-patch.rule;C:\Users\g_top\Desktop\sdktest\python_bump\buildpython37\CMakeFiles\91fb0f334500d963f7f6f7b34afecfa7\python3-configure.rule;C:\Users\g_top\Desktop\sdktest\python_bump\buildpython37\CMakeFiles\91fb0f334500d963f7f6f7b34afecfa7\python3-build.rule;C:\Users\g_top\Desktop\sdktest\python_bump\buildpython37\CMakeFiles\91fb0f334500d963f7f6f7b34afecfa7\python3-install.rule;C:\Users\g_top\Desktop\sdktest\python_bump\buildpython37\CMakeFiles\91fb0f334500d963f7f6f7b34afecfa7\python3-zipPythonSTDlib.rule;C:\Users\g_top\Desktop\sdktest\python_bump\buildpython37\CMakeFiles\91fb0f334500d963f7f6f7b34afecfa7\python3-removePythonSTDlib.rule;C:\Users\g_top\Desktop\sdktest\python_bump\buildpython37\CMakeFiles\b87c1bc3b60e3de3d7a30981d9c2e093\python3-complete.rule;C:\Users\g_top\Desktop\sdktest\python_bump\buildpython37\CMakeFiles\7a1a514ad4022d9ca3e64f5d24924ff2\python3.rule' exited with code 1. [C:\Users\g_top\Desktop\sdktest\python_bump\buildpython37\python3.vcxproj]
````

**Comment by o01eg** [comment]
@geoffthemedio  What is `C:\Users\g_top\Desktop\sdktest\python_bump\buildpython37\python3-prefix\src\python3-build\CMakeFiles\a96301076183e852ffaf2721ca6949ed\importlib_external.h.rule` file?

**Comment by geoffthemedio** [comment]
python37_project_files

After removing that file from the project, the build succeeded.

**Comment by o01eg** [comment]
Wonder what it does and which content it has.

**Comment by o01eg** [comment]
It looks like produced by 
https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/blob/bb45aa7a4cfc7a5a93bc490c6158f702d1a2226f/cmake/libpython/CMakeLists.txt#L480-L509

**Comment by o01eg** [comment]
@geoffthemedio Could you try to manually launch `_freeze_importlib.exe` with `${SRC_DIR}/Lib/importlib/_bootstrap_external.py` and `${SRC_DIR}/Python/importlib_external.h` arguments?

**Comment by geoffthemedio** [comment]
> Could you try to manually launch `_freeze_importlib.exe` with `${SRC_DIR}/Lib/importlib/_bootstrap_external.py` and `${SRC_DIR}/Python/importlib_external.h` arguments?

Not sure what `SRC_DIR` should be. Just running `_freeze_importlib.exe` on its own gives an error saying the application could not be started.

**Comment by o01eg** [comment]
@geoffthemedio How that error looks like?

**Comment by geoffthemedio** [comment]
A system pop saying that the application couldn't be started correctly (0xc00007b). Click OK to close the application.

**Comment by o01eg** [comment]
@geoffthemedio Looks like _freeze_importlib.exe was linked with zlib and required DLL to start. I've add option `CMAKE_MSVCIDE_RUN_PATH` from CMake 3.10 to add it into PATH.

Could you try to test it again?

**Comment by o01eg** [comment]
@geoffthemedio @Vezzra Also, what do you think about fork `https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/` to `freeorion` organization instead of managing pile of patches, and apply here Marcel's patches, Android patches and recent python 3.7 patches? Upstream is regularly dead.

**Comment by geoffthemedio** [comment]
If moving the scripts into a freeorion repository is easier for you to maintain, it's fine with me...

**Comment by Vezzra** [comment]
@o01eg, no objections from my side. Do you need @geoffthemedio or me to set up anything, or do you have all the access rights to do it yourself?

**Comment by o01eg** [comment]
It looks like I cannot fork `python-cmake-buildsystem`.

**Comment by Vezzra** [comment]
Quick link to the forked repo:

https://github.com/freeorion/python-cmake-buildsystem

**Comment by o01eg** [comment]
Tried to switch to it.

**Comment by geoffthemedio** [comment]
using the version from before ~3 min ago, it built the SDK OK. I had to update some include paths in the project files from 3.6 to 3.7, but after that it also built FreeOrion OK.

**Comment by geoffthemedio** [comment]
Latest version also works, at least in Win32 mode, after updating the project file Python paths from 3.6 to 3.7

**Pull request merged**
