### PR TITLE
Prepare release of SDK v13

### PR DESCRIPTION
**Pull request by o01eg**

### CODE REVIEW

**Review by Vezzra — COMMENTED** [review]
The changes look ok to me, and the SDK builds successfully.

However, I can't build FO master with this SDK, but that's probably due to some small adjustments in the FO codebase that are necessary for FO to build with the new version of the SDK.

Here is the build log:
[build.log.zip](https://github.com/freeorion/freeorion-sdk/files/8831981/build.log.zip)

**Comment by o01eg** [comment]
@Vezzra Could you check if append 

```cpp
#include <boost/mpl/vector.hpp>
```

to `parse/PythonParser.cpp` helps?

**Review by Vezzra — APPROVED** [review]

**Comment by Vezzra** [comment]
With this PR merged, is everything ready/done so that I can make a new version of the SDK? Or are there still some things left which need to go in first?

**Comment by o01eg** [comment]
We need to update token as current one is expired, set correct date in `ChangeLog.md`. And somehow deal with Travis CI to make them build release tag.

**Comment by Vezzra** [comment]
I can't offer much help with the update token issue.

Setting the correct date in the changelog can be done right before building the new version of the SDK.

Regarding how to deal with the currently broken build of the SDK on TravisCI, see [my comment here](https://github.com/freeorion/freeorion-sdk/issues/89#issuecomment-1146797506), in the comment section of #89.

**Pull request merged**
