### PR TITLE
[WIP] Update boost 1.72

### PR DESCRIPTION
**Pull request by o01eg**
Supersedes #51 
WIP:
- Wait for release.
- Test freeorion with builds.
- Fix MacOS building.

### CODE REVIEW

**Comment by adrianbroher** [comment]
Is there any reason why this PR is required right now aside from having the latest boost release?  The current master looks ready to ship according to the CI.

**Comment by o01eg** [comment]
@adrianbroher This PR isn't required right now. This PR is only about to have latest boost release.

**Comment by geoffthemedio** [comment]
Also seems to work for Boost 1.74.

**Comment by o01eg** [comment]
Superseded by #70

**Pull request closed without merging**
