### PR TITLE
Mac support

### PR DESCRIPTION
**Pull request by adrianbroher**
This PR should enable the SDK on mac systems.

### CODE REVIEW

**Comment by Vezzra** [comment]
Tried to build the SDK with the latest commits and then tried to build FO with the generated SDK (also moved `GG/Config.h` into the GG tree in my test SDK folder). Not much difference to my last tries, except of course for the `GG/Config.h file not found` errors, which were gone, and some of those `*.pc` files are now in a different (I assume correct) location.

SDK build log layout: [Archiv.zip](https://github.com/freeorion/freeorion-sdk/files/487503/Archiv.zip)

The `ft2build.h file not found` and `pyconfig.h file not found` errors when trying to build FO remained, and the generated SDK layout is still different from the current SDK layout (particularly the Python framework, where the `Headers` symlink apparently is still missing).

**Comment by Vezzra** [comment]
Still no `Header` symlink in the Python framework. The `ft2build.h file not found` error is gone, instead I get a `freetype.h file not found` error. Everything else seems to be as before.

SDK build log and layout: [Archiv.zip](https://github.com/freeorion/freeorion-sdk/files/489713/Archiv.zip)

**Comment by Vezzra** [comment]
FYI: just moved `GG/Config.h` into the GG directory tree in freeorion/freeorion#981. That should take care of the `GG/Config.h file not found` errors, and enable us to remove it from everywhere else.

**Comment by adrianbroher** [comment]
Taking a deeper look into the freetype issue exposes that the MacOSX SDK uses a very old version of freetype (2.3.5) than the Windows SDK (freetype 2.5.5).

Freetype has changed the header layout significantly between those versions.

So what can we do now?

* I can change the `include install dir` to `include` without the `freetype` subdirectory for MacOSX and create a mismatching layout between the manual created SDK and the CMake create one for MacOSX
* You can update the Xcode project to add `ìnclude/freetype` or something like that to update the search path.

**Comment by Vezzra** [comment]
Tried to build the SDK with the most recent mac-support branch, got build errors during the build Python phase.

Build log, cmake error and output log: [Archiv.zip](https://github.com/freeorion/freeorion-sdk/files/505072/Archiv.zip)

> You can update the Xcode project to add `ìnclude/freetype` or something like that to update the search path.

This. Once we got the latest build errors addressed, I'll try to update the Xcode project.

**Comment by adrianbroher** [comment]
> Tried to build the SDK with the most recent mac-support branch, got build errors during the build Python phase.

Yes, there was a typo in one of the python-cmake patches.  It should now build just fine.

**Comment by adrianbroher** [comment]
Closing this now, as the MacOSX SDK builds now on Travis-CI.  Specific issues can be addresses in other issue reports.

**Pull request merged**
