### PR TITLE
CI: Update Artifact actions to v4

### PR DESCRIPTION
**Pull request by o01eg**

### CODE REVIEW

**Comment by o01eg** [comment]
Yes, macos-11 is dropped, and I'm not sure what happening with Windows.

**Comment by o01eg** [comment]
@geoffthemedio I managed to fix build for Windows. Could you test FreeOrion built with new SDL2? SDK is published here https://github.com/o01eg/freeorion-sdk/releases/tag/v15

**Comment by geoffthemedio** [comment]
> v16.

generated zip file still says 14

**Comment by o01eg** [comment]
> generated zip file still says 14

You mean file https://github.com/o01eg/freeorion-sdk/releases/download/v16/FreeOrionSDK_16_MSVC-v143-Win32.zip by my link?

**Comment by geoffthemedio** [comment]
when I build with CMake

**Comment by o01eg** [comment]
Nice, now it's left to fix headers for MacOS Framework.

**Comment by geoffthemedio** [comment]
Bumping Boost to 1.87 would also be useful for testing...

https://github.com/freeorion/freeorion-sdk/compare/master...boost_1_87

**Comment by geoffthemedio** [comment]
I did got some warnings when first running CMake:
````
CMake Warning (dev) at C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.29/Modules/ExternalProject.cmake:3239 (message):
  The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
  not set.  The policy's OLD behavior will be used.  When using a URL
  download, the timestamps of extracted files should preferably be that of
  the time of extraction, otherwise code that depends on the extracted
  contents might not be rebuilt if the URL changes.  The OLD behavior
  preserves the timestamps from the archive instead, but this is usually not
  what you want.  Update your project to the NEW behavior or specify the
  DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
  robustness issue.
Call Stack (most recent call first):
  C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.29/Modules/ExternalProject.cmake:4465 (_ep_add_download_command)
  CMakeLists.txt:509 (ExternalProject_Add)
This warning is for project developers.  Use -Wno-dev to suppress it.
````

**Comment by o01eg** [comment]
@geoffthemedio SDL heavily changed installation so new things installed. Also looks like CMake is updated too and shows warnings about compatibility.

**Review by Vezzra — CHANGES_REQUESTED** [review]
I can build the SDK, but I can't build FO with it. Whether I use the SDK I built manually, or try to build the test commit on your master branch (d69a4a24812c73274c8cda233f78e131645c3450), I get build errors, basically this one error multiple times:

```
In file included from /Users/user/SoftwareProjekte/FO/main/src/client/human/chmain.cpp:1:
In file included from /Users/user/SoftwareProjekte/FO/main/src/client/human/GGHumanClientApp.h:6:
In file included from /Users/user/SoftwareProjekte/FO/main/src/client/human/../../UI/SDLGUI.h:9:
In file included from /Users/user/SoftwareProjekte/FO/main/build/dep/Frameworks/SDL2.framework/Headers/SDL.h:32:
In file included from /Users/user/SoftwareProjekte/FO/main/build/dep/Frameworks/SDL2.framework/Headers/SDL_main.h:25:
/Users/user/SoftwareProjekte/FO/main/build/dep/Frameworks/SDL2.framework/Headers/SDL_stdinc.h:31:10: fatal error: 'SDL_config.h' file not found
#include "SDL_config.h"
```

**Comment by o01eg** [comment]
Yes, I'm trying to disable SDL framework as it's don't work correctly after installation changes in SDL.

**Comment by o01eg** [comment]
Latest try from https://github.com/freeorion/freeorion-sdk/actions/runs/12468283058 should work, but you need to add into FreeOrion's CMakeLists.txt

```cmake
        COMMAND
           ${CMAKE_COMMAND} -E copy_if_different "${SDL_LIBRARIES}" "$<TARGET_FILE_DIR:freeorion>/../SharedSupport"
```

**Comment by o01eg** [comment]
Another try https://github.com/o01eg/freeorion-sdk/releases/tag/v17

**Comment by o01eg** [comment]
MacOS and Windows builds pass https://github.com/o01eg/freeorion/actions/runs/12469666979/job/34803281345

**Review by Vezzra — CHANGES_REQUESTED** [review]
I can now build FO (I build commit 5a787653769b836a6d499b2fdd62c6df3929ac56 from your repo), but the app crashes on startup. Apparently, it can't load `libSDL2-2.0.0.dylib`:
```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               FreeOrion [2663]
Path:                  /Volumes/VOLUME/FreeOrion.app/Contents/MacOS/FreeOrion
Identifier:            org.freeorion.FreeOrion
Version:               0.5.1+ (build 2024-12-23.5a78765) (0.5.1+ o01eg-master (build 2024-12-23.5a78765))
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-12-24 10:22:49.6584 +0100
OS Version:            macOS 12.6 (21G115)
Report Version:        12
Bridge OS Version:     6.6 (19P6067)
Anonymous UUID:        DBE14CFB-5083-F51E-3D62-E711C220B917


Time Awake Since Boot: 6900 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '@rpath/libSDL2-2.0.0.dylib'
Referenced from: '/Volumes/VOLUME/FreeOrion.app/Contents/MacOS/FreeOrion'
Reason: tried: '' (no such file), '' (no such file), '' (no such file), '' (no such file), '' (no such file), '' (no such file)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x10ff0598e __abort_with_payload + 10
1   dyld                          	       0x10ff1ba72 abort_with_payload_wrapper_internal + 80
2   dyld                          	       0x10ff1baa4 abort_with_payload + 9
3   dyld                          	       0x10fec9699 dyld4::halt(char const*) + 615
4   dyld                          	       0x10fec55b5 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3995
5   dyld                          	       0x10fec44e4 start + 388


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x00007ff7bae8d668  rdx: 0x00007ff7bae8dad0
  rdi: 0x0000000000000006  rsi: 0x0000000000000001  rbp: 0x00007ff7bae8d6b0  rsp: 0x00007ff7bae8d668
   r8: 0x00007ff7bae8d6d0   r9: 0x0000000000000000  r10: 0x0000000000000069  r11: 0x0000000000000246
  r12: 0x0000000000000069  r13: 0x00007ff7bae8dad0  r14: 0x0000000000000001  r15: 0x0000000000000006
  rip: 0x000000010ff0598e  rfl: 0x0000000000000246  cr2: 0x0000000105f62000
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133


Binary Images:
       0x10febf000 -        0x10ff2afff dyld (*) <71febccd-d9dc-3599-9971-2b3407c588a8> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=47.1M resident=0K(0%) swapped_out_or_unallocated=47.1M(100%)
Writable regions: Total=9428K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9428K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                         12K        3 
__DATA                             592K        9 
__DATA_CONST                       944K        5 
__LINKEDIT                        21.5M        7 
__TEXT                            25.6M        5 
dyld private memory               1024K        1 
===========                     =======  ======= 
TOTAL                            113.6M       32 
```

**Comment by o01eg** [comment]
@Vezzra Did you make changes in FreeOrion's CMakeLists.txt to copy `libSDL2-2.0.0.dylib` into `SharedSupport` folder?

**Comment by o01eg** [comment]
Oh, I got it built and published as artifact https://github.com/o01eg/freeorion/actions/runs/12485231351 

I have no idea but somehow it links to `libSDL2-2.0.0.dylib` but copies `libSDL2.dylib` to `SharedSupport` folder.

**Comment by o01eg** [comment]
Now I see only `libSDL2.dylib` in SDK, @Vezzra could you try again?

**Comment by o01eg** [comment]
@Vezzra Lastest try from https://github.com/freeorion/freeorion-sdk/actions/runs/12490346595/artifacts/2360950457 looks better, could you check it?

**Comment by Vezzra** [comment]
> @Vezzra Did you make changes in FreeOrion's CMakeLists.txt to copy `libSDL2-2.0.0.dylib` into `SharedSupport` folder?

The line you mentioned above was already there, so I didn't make any changes to CMakeLists.txt.

**Comment by o01eg** [comment]
@geoffthemedio Does the latest Windows SDK works for you?

**Comment by geoffthemedio** [comment]
> @geoffthemedio Does the latest Windows SDK works for you?

Self built or specifically the download?

**Comment by o01eg** [comment]
I suppose downloaded as we mostly use SDKs built by Github Actions.

**Comment by geoffthemedio** [comment]
Downloaded SDK (x64, v143) for Windows built and seems to run OK.

**Pull request merged**
