### PR TITLE
Update SDK Python to 3.9.10

### PR DESCRIPTION
**Pull request by o01eg**

### CODE REVIEW

**Review by Vezzra — APPROVED** [review]
Looks ok AFAICT.

**Comment by o01eg** [comment]
Did you try to build freeorion with it on Windows and MacOS?

**Comment by Vezzra** [comment]
> Did you try to build freeorion with it on Windows and MacOS?

Oh, you want me to test it - no, I didn't have the time for that yet. Will try to get around to it next week...

**Comment by Vezzra** [comment]
Ok, trying to build the SDK on macOS fails. Here is the output to the terminal (the relevant lines):
```
[...]
Scanning dependencies of target python-cmake
[ 10%] Creating directories for 'python-cmake'
[ 12%] Performing download step (download, verify and extract) for 'python-cmake'
-- Downloading...
   dst='/Users/user/SoftwareProjekte/FO/sdk/build/downloads/bb45aa7a4cfc7a5a93bc490c6158f702d1a2226f.zip'
   timeout='none'
-- Using src='https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/archive/bb45aa7a4cfc7a5a93bc490c6158f702d1a2226f.zip'
-- [download 100% complete]
-- verifying file...
       file='/Users/user/SoftwareProjekte/FO/sdk/build/downloads/bb45aa7a4cfc7a5a93bc490c6158f702d1a2226f.zip'
-- Downloading... done
-- extracting...
     src='/Users/user/SoftwareProjekte/FO/sdk/build/downloads/bb45aa7a4cfc7a5a93bc490c6158f702d1a2226f.zip'
     dst='/Users/user/SoftwareProjekte/FO/sdk/build/python-cmake-prefix/src/python-cmake'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 13%] Performing patch step for 'python-cmake'
patching file cmake/extensions/CMakeLists.txt
Hunk #1 succeeded at 10 with fuzz 2 (offset -17 lines).
Hunk #2 FAILED at 25.
Hunk #3 FAILED at 39.
Hunk #4 FAILED at 67.
Hunk #5 FAILED at 85.
4 out of 5 hunks FAILED -- saving rejects to file cmake/extensions/CMakeLists.txt.rej
make[2]: *** [python-cmake-prefix/src/python-cmake-stamp/python-cmake-patch] Error 1
make[1]: *** [CMakeFiles/python-cmake.dir/all] Error 2
make: *** [all] Error 2
```
Not entirely unexpected - there are a couple of patches which need to be applied to the Python cmake files, and those of course won't apply correctly with the cmake files of a different Python version.

Unfortunately I have no idea how to fix this. However, someone obviously had been able to do this for the last SDK versions (maybe that was you, @o01eg?), when we last updated the Python version. I hope you have an idea what to do about those patches...

**Comment by o01eg** [comment]
`0001-...` was adoped to upstream I see. I've removed it but later I'll check other patches.

**Comment by Vezzra** [comment]
> ...  later I'll check other patches

Ok, tell me when you're done with checking the patches, then I'll try again.

**Comment by o01eg** [comment]
@Vezzra Could you try again?

I reimported patches to python-cmake git, rebased them and reformatted them as patches.

**Comment by o01eg** [comment]
Also, could we make something with broken CI here?

**Review by Vezzra — DISMISSED** [review]
Patching the Python cmake files seems to work now, but the subsequent cmake configure step fails with this error:
```
CMake Error at CMakeLists.txt:870 (endif):
  endif An ENDIF command was found outside of a proper IF ENDIF structure.
  Or its arguments did not match the opening IF command.
```
Complete cmake console output attached:
[cmake_output.txt.zip](https://github.com/freeorion/freeorion-sdk/files/8660041/cmake_output.txt.zip)

**Comment by Vezzra** [comment]
Here is the cmake file the error message refers to (I think). There is a lonely `endif` statement on the indicated line, I hope you can figure out how that happened/how to fix it. I guess some of the patching, while not failing with an error, still doesn't work as it should...?

[CMakeLists.txt.zip](https://github.com/freeorion/freeorion-sdk/files/8660099/CMakeLists.txt.zip)

**Review by Vezzra — COMMENTED** [review]
The SDK builds successfully now, but I can't build FO master with that SDK. It fails during the cmake configure step, cmake output is this:
```
-- Setting build type to 'Release' as none was specified.
-- Build type CMAKE_BUILD_TYPE set to Release
-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Use CCache for Xcode called with: ccache program  
-- Performing Test NOT_GNU_CXX_BUG_94190
-- Performing Test NOT_GNU_CXX_BUG_94190 - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found PythonInterp: /usr/local/bin/python3 (found suitable version "3.8.3", minimum required is "3.6") 
-- Found PythonLibs: /Library/Frameworks/Python.framework/Versions/3.8/lib/libpython3.8.dylib (found suitable version "3.8.3", minimum required is "3.6") 
-- Python library version detected 3.8.3
-- Boost python version 38
CMake Warning at cmake/FindBoost.cmake:924 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  cmake/FindBoost.cmake:1046 (_Boost_COMPONENT_DEPENDENCIES)
  cmake/FindBoost.cmake:1736 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:254 (find_package)


CMake Warning at cmake/FindBoost.cmake:924 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  cmake/FindBoost.cmake:1046 (_Boost_COMPONENT_DEPENDENCIES)
  cmake/FindBoost.cmake:1736 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:254 (find_package)


CMake Warning at cmake/FindBoost.cmake:924 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  cmake/FindBoost.cmake:1046 (_Boost_COMPONENT_DEPENDENCIES)
  cmake/FindBoost.cmake:1736 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:254 (find_package)


CMake Warning at cmake/FindBoost.cmake:924 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  cmake/FindBoost.cmake:1046 (_Boost_COMPONENT_DEPENDENCIES)
  cmake/FindBoost.cmake:1736 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:254 (find_package)


CMake Warning at cmake/FindBoost.cmake:924 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  cmake/FindBoost.cmake:1046 (_Boost_COMPONENT_DEPENDENCIES)
  cmake/FindBoost.cmake:1736 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:254 (find_package)


CMake Warning at cmake/FindBoost.cmake:924 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  cmake/FindBoost.cmake:1046 (_Boost_COMPONENT_DEPENDENCIES)
  cmake/FindBoost.cmake:1736 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:254 (find_package)


CMake Warning at cmake/FindBoost.cmake:924 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  cmake/FindBoost.cmake:1046 (_Boost_COMPONENT_DEPENDENCIES)
  cmake/FindBoost.cmake:1736 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:254 (find_package)


CMake Warning at cmake/FindBoost.cmake:924 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  cmake/FindBoost.cmake:1046 (_Boost_COMPONENT_DEPENDENCIES)
  cmake/FindBoost.cmake:1736 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:254 (find_package)


CMake Warning at cmake/FindBoost.cmake:924 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  cmake/FindBoost.cmake:1046 (_Boost_COMPONENT_DEPENDENCIES)
  cmake/FindBoost.cmake:1736 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:254 (find_package)


CMake Warning at cmake/FindBoost.cmake:924 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  cmake/FindBoost.cmake:1046 (_Boost_COMPONENT_DEPENDENCIES)
  cmake/FindBoost.cmake:1736 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:254 (find_package)


CMake Warning at cmake/FindBoost.cmake:924 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  cmake/FindBoost.cmake:1046 (_Boost_COMPONENT_DEPENDENCIES)
  cmake/FindBoost.cmake:1736 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:254 (find_package)


CMake Warning at cmake/FindBoost.cmake:924 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  cmake/FindBoost.cmake:1046 (_Boost_COMPONENT_DEPENDENCIES)
  cmake/FindBoost.cmake:1736 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:254 (find_package)


-- Boost version: 1.74.0
-- Found the following Boost libraries:
--   filesystem
--   iostreams
--   locale
--   log
--   log_setup
--   serialization
--   system
--   thread
--   regex
--   date_time
--   chrono
--   atomic
CMake Warning at cmake/FindBoost.cmake:924 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  cmake/FindBoost.cmake:1046 (_Boost_COMPONENT_DEPENDENCIES)
  cmake/FindBoost.cmake:1736 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:266 (find_package)


-- Boost version: 1.74.0
-- Found the following Boost libraries:
CMake Warning at cmake/FindBoost.cmake:924 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  cmake/FindBoost.cmake:1046 (_Boost_COMPONENT_DEPENDENCIES)
  cmake/FindBoost.cmake:1736 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:270 (find_package)


CMake Error at cmake/FindBoost.cmake:2174 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.74.0

  Boost include path: /Users/user/SoftwareProjekte/FO/main/build/dep/include

  Could not find the following Boost libraries:

          boost_python3

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:270 (find_package)


-- Found ZLIB: /Users/user/SoftwareProjekte/FO/main/build/dep/lib/libz.a (found version "1.2.11") 
-- Found SDL: /Users/user/SoftwareProjekte/FO/main/build/dep/Frameworks/SDL2.framework (found version "2.0.12") 
-- Found Freetype: /Users/user/SoftwareProjekte/FO/main/build/dep/lib/libfreetype.a (found version "2.9.0") 
-- Found OpenGL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework   
-- Found OpenAL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenAL.framework  
-- Found Ogg: /Users/user/SoftwareProjekte/FO/main/build/dep/Frameworks/ogg.framework  
-- Found Vorbis: /Users/user/SoftwareProjekte/FO/main/build/dep/Frameworks/vorbis.framework   
CMake Warning at cmake/FindBoost.cmake:924 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  cmake/FindBoost.cmake:1046 (_Boost_COMPONENT_DEPENDENCIES)
  cmake/FindBoost.cmake:1736 (_Boost_MISSING_DEPENDENCIES)
  GG/CMakeLists.txt:66 (find_package)


CMake Warning at cmake/FindBoost.cmake:924 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  cmake/FindBoost.cmake:1046 (_Boost_COMPONENT_DEPENDENCIES)
  cmake/FindBoost.cmake:1736 (_Boost_MISSING_DEPENDENCIES)
  GG/CMakeLists.txt:66 (find_package)


CMake Warning at cmake/FindBoost.cmake:924 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  cmake/FindBoost.cmake:1046 (_Boost_COMPONENT_DEPENDENCIES)
  cmake/FindBoost.cmake:1736 (_Boost_MISSING_DEPENDENCIES)
  GG/CMakeLists.txt:66 (find_package)


-- Boost version: 1.74.0
-- Found the following Boost libraries:
--   filesystem
--   regex
--   system
-- Found GLEW: /Users/user/SoftwareProjekte/FO/main/build/dep/include  
-- Found PNG: /Users/user/SoftwareProjekte/FO/main/build/dep/lib/libpng.a (found version "1.6.37") 
Build number matches build number in existing Version.cpp, skip regenerating it
Build number matches build number in existing Version.cpp, skip regenerating it
Building v0.4.10+ build 2022-05-09.3abfde4
-- Could NOT find CPPCheck (missing: CPPCHECK_EXECUTABLE) 
-- Could NOT find Flake8 (missing: FLAKE8_EXECUTABLE) 
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
INSTALL TARGETS - target freeorion has RESOURCE files but no RESOURCE DESTINATION.
-- Configuring incomplete, errors occurred!
See also "/Users/user/SoftwareProjekte/FO/main/build/CMakeFiles/CMakeOutput.log".
```

**Comment by o01eg** [comment]
@Vezzra  It found incorrect python installation. Could you point it to 3.9 python with -DPYTHON_EXECUTABLE ?

**Comment by Vezzra** [comment]
@o01eg,

>  It found incorrect python installation. Could you point it to 3.9 python with -DPYTHON_EXECUTABLE ?

Ah, ok. Tried that now, however, I didn't use `-DPYTHON_EXECUTABLE`, but adjusted lines 117 and 245 in `CMakeLists.txt` to Python version 3.9. Anyway, it worked. Can build and run FO with the new SDK now.

I run the test on my Mac, do you need me to do that test also on Windows?

**Review by Vezzra — APPROVED** [review]

**Comment by o01eg** [comment]
Yes, but I suppose it will be simpler as Windows doesn't tend to have system-wide installed python.

**Comment by geoffthemedio** [comment]
On Windows, building the SDK seems to work, but the resulting zip is slightly oddly named: **FreeOrionSDK_12_MSVC-v142-.zip**

**Comment by o01eg** [comment]
```cmake
set(DIST_TOOLSET ${DIST_TOOLSET}-${_VS_PLATFORM_TOOLSET}-${CMAKE_GENERATOR_PLATFORM})
```

@geoffthemedio Looks like CMAKE_GENERATOR_PLATFORM is empty. Not sure if it cause by python change.

**Comment by geoffthemedio** [comment]
After running **bootstrap.bat** and loading the .sln file for MSVC 2019 and building, I get about 16000 linker errors:
````
5>   Creating library ../../FreeOrionD.lib and object ../../FreeOrionD.exp
5>Parsers.lib(PlanetSizeValueRefParser.obj) : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static void __cdecl boost::log::v2_mt_nt6::attribute::impl::operator delete(void *,unsigned int)" (__imp_??3impl@attribute@v2_mt_nt6@log@boost@@SAXPAXI@Z)
5>Parsers.lib(UniverseObjectTypeValueRefParser.obj) : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static void __cdecl boost::log::v2_mt_nt6::attribute::impl::operator delete(void *,unsigned int)" (__imp_??3impl@attribute@v2_mt_nt6@log@boost@@SAXPAXI@Z)
5>Parsers.lib(StarTypeValueRefParser.obj) : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static void __cdecl boost::log::v2_mt_nt6::attribute::impl::operator delete(void *,unsigned int)" (__imp_??3impl@attribute@v2_mt_nt6@log@boost@@SAXPAXI@Z)
5>Parsers.lib(EffectParser3.obj) : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static void __cdecl boost::log::v2_mt_nt6::attribute::impl::operator delete(void *,unsigned int)" (__imp_??3impl@attribute@v2_mt_nt6@log@boost@@SAXPAXI@Z)
````
````
4>Common.lib(PythonCommon.obj) : error LNK2001: unresolved external symbol __imp__PyEval_CallFunction
4>Common.lib(PythonCommon.obj) : error LNK2001: unresolved external symbol __imp__PyObject_Size
4>Parsers.lib(PythonParser.obj) : error LNK2001: unresolved external symbol __imp__PyObject_Size
4>Parsers.lib(ValueRefPythonParser.obj) : error LNK2001: unresolved external symbol __imp__PyObject_Size
4>Common.lib(PythonCommon.obj) : error LNK2001: unresolved external symbol __imp__Py_DecodeLocale
4>Parsers.lib(EnumPythonParser.obj) : error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl boost::python::throw_error_already_set(void)" (__imp_?throw_error_already_set@python@boost@@YAXXZ)
4>Parsers.lib(ConditionPythonParser.obj) : error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl boost::python::throw_error_already_set(void)" (__imp_?throw_error_already_set@python@boost@@YAXXZ)
4>Parsers.lib(ValueRefPythonParser.obj) : error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl boost::python::throw_error_already_set(void)" (__imp_?throw_error_already_set@python@boost@@YAXXZ)
4>Parsers.lib(SourcePythonParser.obj) : error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl boost::python::throw_error_already_set(void)" (__imp_?throw_error_already_set@python@boost@@YAXXZ)

````

**Comment by o01eg** [comment]
I suppose solution should change python library path

**Comment by geoffthemedio** [comment]
Maybe, but it's not just Python-related linker errors... also FreeType, Boost, GLEW, ...

**Comment by o01eg** [comment]
I support release v12 isn't be able to build either on Windows?

**Comment by geoffthemedio** [comment]
SDK12 has worked for me since release

**Comment by o01eg** [comment]
What if rebuild SDK from v12 same way and try to use it?

**Comment by o01eg** [comment]
Could you manually choose `-G "Visual Studio 15" -T v141 -A Win32` when building SDK? Maybe default settings are incorrect?

**Comment by geoffthemedio** [comment]
With **cmake .. -T v142 -A Win32** the filename looks fixed.

**Comment by o01eg** [comment]
`-T v141` is used in Travis for better compatibility. Maybe link issues was caused by v142 SDK and solution set up for v141.

**Comment by geoffthemedio** [comment]
v141 and v142 are supposed to be intercompatible. Can try again with v141 though.

**Comment by geoffthemedio** [comment]
still getting
````
2>   Creating library ../../GiGi.lib and object ../../GiGi.exp
2>GLClientAndServerBuffer.obj : error LNK2001: unresolved external symbol __imp____glewBindBuffer
2>VectorTexture.obj : error LNK2001: unresolved external symbol __imp____glewBindBuffer
2>GLClientAndServerBuffer.obj : error LNK2001: unresolved external symbol __imp____glewBufferData
2>VectorTexture.obj : error LNK2001: unresolved external symbol __imp____glewBufferData
2>GLClientAndServerBuffer.obj : error LNK2001: unresolved external symbol __imp____glewDeleteBuffers
2>VectorTexture.obj : error LNK2001: unresolved external symbol __imp____glewDeleteBuffers
2>GLClientAndServerBuffer.obj : error LNK2001: unresolved external symbol __imp____glewGenBuffers
````

**Comment by geoffthemedio** [comment]
OK, master SDK is also getting link errors. dunno when that started happening, but my local builds with SDK12 have been working fine.

**Comment by o01eg** [comment]
I suppose glew issue is https://github.com/freeorion/freeorion-sdk/issues/67

**Comment by o01eg** [comment]
Does glew build as x64 even if `-A Win32` was set?

**Comment by geoffthemedio** [comment]
> Does glew build as x64 even if `-A Win32` was set?

I think that's what's happening. At least the generated .sln appears to be x64 and the resulting files work the same as the ones in the .zip

**Comment by o01eg** [comment]
`-DCMAKE_OSX_ARCHITECTURES` is set by out SDK's `CMakeLists.txt`. Maybe set it only for MacOS.

**Comment by geoffthemedio** [comment]
I tried bulding the SDK and then FreeOrion in x64 mode, and it seems to work. Just had to tweak the FreeOrion MSVC project files somewhat. Maybe that's the solution going forward? Switch to x64 builds?

**Comment by o01eg** [comment]
@geoffthemedio I've opened PR to fix possible choose of wrong architecture in GLEW https://github.com/freeorion/freeorion-sdk/pull/90

**Comment by hifron** [comment]
If building FO on Windows 11 with VS 22, there is needed 32bit Python and compiling with VS Code needs choosing VS compiler version amd64_x86 (that's compiling on 64bit architecture for 32bit app)... But 32bit version of compilers and its testing for production is probably no more so tested including recent problems on Windows Server 2022 when were present various malfunctions in practice...

MacOS problems could maybe resolved by switching MacOS to version 11 instead of 10.something(10.15?)... There is already version MacOS 12 in beta, which maybe next year will be actual, who knows... https://github.com/actions/virtual-environments

**Comment by geoffthemedio** [comment]
SDK builds seemingly OK. Building FreeOrion with CMake gives errors:
````
C:\Users\g_top\Desktop\FOSDK14\FreeOrion\build>cmake .. -G "Visual Studio 17 2022" -T v143 -A x64 -DBUILD_TESTING=On -DCMAKE_C_FLAGS=/MP -DCMAKE_CXX_FLAGS=/MP -DPYTHON_EXECUTABLE="C:\Users\g_top\Desktop\FOSDK14\bin\python3.9.exe" -DPYTHON_LIBRARY="C:\Users\g_top\Desktop\FOSDK14\lib\python39.lib" -DPYTHON_INCLUDE_DIR="C:\Users\g_top\Desktop\FOSDK14\include\python3.9\"

[...]

Traceback (most recent call last):
  File "C:\Users\g_top\Desktop\FOSDK14\bin\python39.zip\subprocess.py", line 74, in <module>
ModuleNotFoundError: No module named '_winapi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\g_top\Desktop\FOSDK14\FreeOrion\cmake\make_versioncpp.py", line 8, in <module>
    from platform import system
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\g_top\Desktop\FOSDK14\bin\python39.zip\platform.py", line 119, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\g_top\Desktop\FOSDK14\bin\python39.zip\subprocess.py", line 78, in <module>
ModuleNotFoundError: No module named '_posixsubprocess'
CMake Error at CMakeLists.txt:371 (message):
  FreeOrion version failed


-- Configuring incomplete, errors occurred!
See also "C:/Users/g_top/Desktop/FOSDK14/FreeOrion/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/g_top/Desktop/FOSDK14/FreeOrion/build/CMakeFiles/CMakeError.log".

C:\Users\g_top\Desktop\FOSDK14\FreeOrion\build>
````

[CMakeOutput.log](https://github.com/freeorion/freeorion-sdk/files/11191865/CMakeOutput.log)
[CMakeError.log](https://github.com/freeorion/freeorion-sdk/files/11191866/CMakeError.log)

**Comment by o01eg** [comment]
That because I set `-DENABLE_WINAPI=OFF`. I copied it from attempt year ago, not sure what was wrong here.

**Comment by o01eg** [comment]
I've just published built SDK at https://github.com/o01eg/freeorion-sdk/releases/tag/v14

**Comment by o01eg** [comment]
Updated branch [macos-python-no-framework](https://github.com/o01eg/freeorion/tree/macos-python-no-framework) for it.

Also made artifacts from it for MacOS: https://github.com/o01eg/freeorion/actions/runs/4676648333

**Comment by geoffthemedio** [comment]
builds OK with CMake when specifying the python pathes. didn't try without specifying them.

**Comment by o01eg** [comment]
Nice, wait for @Vezzra for result. I've updated minimum MacOS version for boost also https://github.com/freeorion/freeorion-sdk/pull/107#pullrequestreview-1111572970

**Comment by o01eg** [comment]
@Vezzra May be only test if artifact works.

**Comment by Vezzra** [comment]
Ok, I did test it anyway, and I get errors now. I can build the SDK, but building FO with that SDK fails.

Build logs: [build_logs.zip](https://github.com/freeorion/freeorion-sdk/files/11233159/build_logs.zip)

**Comment by o01eg** [comment]
@Vezzra  I've add fixes to my branch [macos-python-no-framework](https://github.com/o01eg/freeorion/tree/macos-python-no-framework)

**Comment by o01eg** [comment]
I propose to release SDK after merging this PR.

**Comment by Vezzra** [comment]
> I propose to release SDK after merging this PR.

Any PRs in the main freeorion repo that need to get merged into master for master to successfully build and run with the new version of the SDK?

**Comment by o01eg** [comment]
@Vezzra I didn't open mine PR yet from [macos-python-no-framework](https://github.com/o01eg/freeorion/tree/macos-python-no-framework)

**Pull request merged**
