### PR TITLE
Add python3 support

### LINKED ISSUE #47: Add python3 to Windows and MacOS SDKs
To follow up #46 and to move forward in python 3 migration (https://freeorion.org/forum/viewtopic.php?f=9&t=11181) there should be support for python 3 in Windows and MacOS SDKs as well.

### PR DESCRIPTION
**Pull request by o01eg**
This PR is the rebased @adrianbroher `python3` branch with python 3.5.7 update and some fixes.

Fixes #47 . Supersedes #50  

There both `python3.{dll,lib,pdb}` and `python35.{dll,lib,pdb}`. Those libraries are different. Is it intended?

### CODE REVIEW

**Comment by adrianbroher** [comment]
> There both python3.{dll,lib,pdb} and python35.{dll,lib,pdb}. Those libraries are different. Is it intended?

Probably not, but the referenced `python-cmake` is a good mile behind the latest development.

**Comment by o01eg** [comment]
> Probably not, but the used `python-cmake` is a good mile behind the latest development.

I've updated python-cmake for latest commit, it successfully builds python but python3.{lib,dll} and python35.{lib,dll} still exists both.

**Comment by o01eg** [comment]
Also for both python2 and python3 support boost should be updated to 1.67:
> The library name now includes the version suffix of the Python version used to compile it. For example, a variant compiled with Python 2.7 will produce library names boost_python27 and boost_numpy27, etc.. Combined with a related fix in Boost.Build, this means that it is now possible to build variants for multiple Python versions in a single build process.

But I get strange error:

      ...skipped <pbin.v2\libs\log\build\msvc-14.0\rls\adrs-mdl-64\dbg-str-dtbs\dbg-symbl-on\pch-off\thrdp-wn32\thrd-mlt>attribute_name.obj for lack of <pbin.v2\standalone\msvc\msvc-14.0>msvc-setup.nup...

**Comment by o01eg** [comment]
If I simply update boost to 1.67 CI only builds `boost_python27.{dll,lib}`. If I force to build both python with `python=2.7 python=3.5` I got errors.

**Comment by o01eg** [comment]
Rebased on top https://github.com/freeorion/freeorion-sdk/pull/49 to test with boost 1.68

**Comment by o01eg** [comment]
Both python support was fixed in 1.70 but there GIL issues to update to this boost version.

**Comment by o01eg** [comment]
As https://github.com/freeorion/freeorion/issues/2468 found to be fixed this PR is ready to be merged as well.

**Comment by Vezzra** [comment]
Anything preventing merge?

**Comment by o01eg** [comment]
I didn't found issues with this SDK.

**Comment by geoffthemedio** [comment]
If you think it's good and no-one objects, then I suggest merging...

**Pull request merged**
