### PR TITLE
Update boost 1.70

### PR DESCRIPTION
**Pull request by o01eg**
Extracted from #49 and supersedes it.

### CODE REVIEW

**Comment by o01eg** [comment]
Looks like https://github.com/freeorion/freeorion/issues/2468 was caused by my incorrect build environment. It builds freeorion now.

**Comment by Vezzra** [comment]
> Looks like https://github.com/freeorion/freeorion/issues/2468 was caused by my incorrect build environment. It builds freeorion now.

@o01eg, so, can we close this? Or should it be merged nonetheless?

**Comment by o01eg** [comment]
@Vezzra Depends on #48. Will it be merged?

**Comment by Vezzra** [comment]
No objections against merging #48 from my side, but I'm so out of touch with what's going on with the SDK that my opinion doesn't really count.

Anyone else? With @adrianbroher gone, who takes care of the SDK?

**Pull request merged**
