### PR TITLE
Update to Boost 1.74

### PR DESCRIPTION
**Pull request by geoffthemedio**
Based on @o01eg 's equivalent for Boost 1.72

Updates the URL and MD5.

Also updates GLEW to 2.2.0, SDL to 2.0.12, PNG to 1.6.37

Also updates README files and travis.yml for XCode

### CODE REVIEW

**Comment by geoffthemedio** [comment]
@Vezzra testing this would be appreciated when you have time...

**Comment by Vezzra** [comment]
@geoffthemedio, when trying to build the SDK with this PR, I get the following error message:
```
/Users/user/SoftwareProjekte/FO/sdk/build/boost-prefix/src/boost/tools/build/src/build/feature.jam:327: in validate-feature from module feature
error: unknown feature "<macosx-version-min>"
```
Apparently that flag/feature of the boost build system has been deprecated? The question is, how to specify the min macOS version the libraries need to be compatible then?

**Comment by geoffthemedio** [comment]
related to https://www.freeorion.org/forum/viewtopic.php?p=82710#p82710 ?

**Comment by Vezzra** [comment]
> related to https://www.freeorion.org/forum/viewtopic.php?p=82710#p82710 ?

I'm not sure what you mean - the issue mentioned there is that specifying the `macosx-version-min` option had been necessary to be able to build Boost on Mac, at least back then.

I assumed it also makes sure that the Boost libraries getting built are compatible at least with the macOS version specified. I wasn't sure what would happen if we just omit the option.

Then I proceeded with this test:

> maybe try without https://github.com/freeorion/freeorion-sdk/blob/master/patches/boost/0005-Fix-min-MacOSX-version.patch

Gives the same error. However, if removing that option entirely, the SDK builds successfully. Building and running FO with that SDK works too.

The problem is, I don't know for sure how combatibility with older macOS versions is affected. The SDK and FO have been built on macOS 10.14, running the FO build on an older Mac with macOS 10.11 worked. Apparently it is possible to build Boost without specifying the `macosx-version-min` option, linking FO against it and run it on older macOS versions, but, as I said, not entirely sure about it. I don't know what the option really did originally...

Good enough for you to just drop the option and trust that things will work...?

**Comment by o01eg** [comment]
Could we use minimum compatible MacOS version with CI?

**Comment by geoffthemedio** [comment]
> Could we use minimum compatible MacOS version with CI?

Not sure what that means. Change the settings for the Travis build, or make changes to the OSX build based on what works in TravisCI...?

**Comment by geoffthemedio** [comment]
> Good enough for you to just drop the option and trust that things will work...?

If it works for you, that's enough for me. Particularly for OSX, I don't think corner cases like SDK building need to have excessively robust support older OS releases...

**Comment by geoffthemedio** [comment]
> > Could we use minimum compatible MacOS version with CI?
> 
> Not sure what that means. Change the settings for the Travis build, or make changes to the OSX build based on what works in TravisCI...?

@o01eg could you explain?

**Comment by o01eg** [comment]
@geoffthemedio Use Travis CI MacOS version as minimum compatible for project.

**Comment by geoffthemedio** [comment]
> 
> 
> @geoffthemedio Use Travis CI MacOS version as minimum compatible for project.

Still not clear... Do you mean take the current MacOS version set for the Travis CI build and declare that to be the minimum version supported by FreeOrion, or set the Travis CI build to some other number that is determined to be the minimum needed to build or to run FreeOrion, or something else...?

**Comment by o01eg** [comment]
> Do you mean take the current MacOS version set for the Travis CI build and declare that to be the minimum version supported by FreeOrion

Yes

**Comment by geoffthemedio** [comment]
That's probably still a few versions past, so probably fine for MacOS... @Vezzra ?

**Comment by Vezzra** [comment]
@geoffthemedio,

> That's probably still a few versions past, so probably fine for MacOS

Probably... what is the MacOS version currently set for the Travis CI build?

**Comment by geoffthemedio** [comment]
For the SDK and FreeOrion TravisCI builds, the XCode version is set to 9.4:
https://github.com/freeorion/freeorion-sdk/blame/master/.travis.yml#L53
https://github.com/freeorion/freeorion/blame/master/.travis.yml#L128
which reportedly needs at least MacOS 10.13.2 to run:
https://en.wikipedia.org/wiki/Xcode#Xcode_1.0_-_Xcode_2.x_(before_iOS_support)

**Comment by Vezzra** [comment]
@geoffthemedio,

if I understand correctly, this CI thing works by launching a virtual machine, setting up a build environment within that VM and then build FO with that build environment. Obviously the platform which should be run inside the VM needs to be specified, isn't that also the case for the exact version of that platform?

Meaning, I expected that the macOS version used by the CI has to be specified somewhere, and that's the macOS min version we are talking about.

That said, macOS 10.13 is quite recent, just three years old. Requiring that for the SDK (that is, for being able to do developing work on/build FO) is probably fine, but for running FO that would be a bit harsh. I was hoping that we could always support FO on macOS versions at least 4-5 years old.

Of course, if there is no way around it, we just have to live with it. As I said earlier, the playerbase on Mac isn't exactly huge...

**Comment by geoffthemedio** [comment]
Perhaps it doesn't matter what version of MacOS is used as long as it supports the specified version of XCode?

That said, older TravisCI build logs (from when they actually ran on SDK commits) specify the system info used, eg: https://travis-ci.org/github/freeorion/freeorion-sdk/jobs/741929795#L15
[code]Build image provisioning date and time
Fri Dec 13 04:54:58 GMT 2019
Operating System Details
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65[/code]

**Comment by Vezzra** [comment]
> Perhaps it doesn't matter what version of MacOS is used as long as it supports the specified version of XCode?

Doesn't matter for what? Which version of macOS the resulting FO build will run on? In that case, yes, it doesn't matter on which version of macOS FO is being build, what matters is which version is specified as the minimum version the resulting build should be able to run on (Xcode can do that, building for older macOS versions than the one it is running on).

But if I understand correctly, the suggestion is to "...take the current MacOS version set for the Travis CI build and declare that to be the minimum version supported by FreeOrion". Which would be 10.13 in our case. And if you build for 10.13, it most likely will only run on 10.13 or later.

Which means we would only support macOS versions not older than 3 years. As I said, not ideal, but if there is no way around it (at least not without too much effort), then we can probably live with that.

**Comment by geoffthemedio** [comment]
> Then I proceeded with this test:
> 
> > maybe try without https://github.com/freeorion/freeorion-sdk/blob/master/patches/boost/0005-Fix-min-MacOSX-version.patch
> 
> Gives the same error. However, if removing that option entirely, the SDK builds successfully. Building and running FO with that SDK works too.

What did you mean by "removing that option entirely" that was different than building the SDK without that patch? The current patch is
````
--- a/tools/build/src/tools/darwin.jam	2020-11-16 19:46:41.088054801 +0300
+++ b/tools/build/src/tools/darwin.jam	2020-11-16 19:47:07.481053385 +0300
@@ -29,6 +29,7 @@
 
 ## The minimal MacOSX version to target.
 feature macosx-version-min : : propagated optional ;
+feature.extend macosx-version-min : 10.9 ;
 
 ## A dependency, that is forced to be included in the link.
 feature force-load : : free dependency incidental ;
````
If deleting that patch file doesn't do the same thing, what did you do instead? Can you make a patch that does that?

If we're going to make a new SDK release for Python 3.6 then I'd like to put updated Boost in as well.

**Comment by Vezzra** [comment]
@geoffthemedio,

> What did you mean by "removing that option entirely" that was different than building the SDK without that patch?

Ugh, you're asking about something I did last November... I'm an old man, you know, my memory isn't what it used to be... 😉 

> If deleting that patch file doesn't do the same thing, what did you do instead?

IIRC what I tried was building without the patch, but still specifying the `macosx-version-min` option on the command line. Only when building without the patch *and* not specifying the option on the command line (thus "removing it completely") things worked.

However, what I'm worried about is, when not specifying anywhere what min macOS version I want to build for, how does the Boost build system determine the min macOS version the resulting libraries will/should work on...?

**Comment by geoffthemedio** [comment]
Probably it will be determined by the minimum version that is supported by the version of XCode that is being used to compile?

**Comment by Vezzra** [comment]
Maybe? I have no idea...

**Comment by geoffthemedio** [comment]
@Vezzra [with the OSC patch removed](https://travis-ci.com/github/freeorion/freeorion-sdk/jobs/486568337#L9653), I get errors about `error: unknown feature "<macosx-version-min>"`. Any suggestions what else I need to change to fix that?

**Comment by Vezzra** [comment]
@geoffthemedio, you need to remove [line 523](https://github.com/freeorion/freeorion-sdk/blob/74c693d00c393e2857fd98df07131b095027169d/CMakeLists.txt#L523) from `CMakeKists.txt`.

I remember now - this was what I meant with "removing that option entirely": you need to remove the patch and that line, so the option does not get specified anywhere. Apparently it has been deprecated...

**Comment by geoffthemedio** [comment]
Does this work for you on MacOS now @Vezzra ?

The [MSVC builds on TravisCI are failing](https://travis-ci.com/github/freeorion/freeorion-sdk/jobs/490266910#L1578) for reasons I don't understand, but my local tests seem OK.

**Comment by geoffthemedio** [comment]
@o01eg Do you have any idea how to fix the build errors on Travis?

https://travis-ci.com/github/freeorion/freeorion-sdk/jobs/490860054#L1526

**Comment by o01eg** [comment]
No, it looks like boost somehow use `g++` instead of `cl`. Should be option somewhere I think.

**Comment by o01eg** [comment]
Could you try to add `choco uninstall mingw` before build?

**Comment by geoffthemedio** [comment]
Now [it says](https://travis-ci.com/github/freeorion/freeorion-sdk/jobs/490877692#L1572)
`'g++' is not recognized as an internal or external command,`

**Comment by o01eg** [comment]
Yes, maybe it should be mentioned in `boost-config.jam` now to use msvc

**Comment by o01eg** [comment]
Log shows strange environment variables:

```
$ export TRAVIS_COMPILER=cl
$ export CXX=${CXX:-g++}
$ export CXX_FOR_BUILD=${CXX_FOR_BUILD:-g++}
$ export CC=${CC:-gcc}
$ export CC_FOR_BUILD=${CC_FOR_BUILD:-gcc}
```

**Comment by geoffthemedio** [comment]
> Log shows strange environment variables:

Looks the same [in master, which builds OK](https://travis-ci.com/github/freeorion/freeorion-sdk/jobs/490374413#L22):

**Comment by o01eg** [comment]
Could we try to output `bootstrap.log` file?

**Comment by geoffthemedio** [comment]
> Could we try to output `bootstrap.log` file?

Not sure how. I found a few references to uploading things to an Amazon cloud account of some sort. There are about 5 build and scripting systems interacting here, so I have no idea what to change or what to search for to how to do so.

**Comment by Vezzra** [comment]
@geoffthemedio,

> Does this work for you on MacOS now

Yes. I can build the SDK, build and run current master of FO, and launch a default quickstart game. Everything seems to work fine.

Can't say anything about which not so recent versions of macOS are supported now. Tested on macOS 10.14, so that at least is covered.

**Comment by o01eg** [comment]
This version have fixed symbolic links on Windows

**Comment by o01eg** [comment]
@geoffthemedio @Vezzra Looks like environment variables caused issue with boost 1.74 https://github.com/freeorion/freeorion-sdk/pull/83

**Comment by geoffthemedio** [comment]
seemingly superceded by #83

**Pull request closed without merging**
