### PR TITLE
Update SDL to 2.0.10

### PR DESCRIPTION
**Pull request by geoffthemedio**
There is a compatability issue between SDL 2.0.8 and the Windows SDK version 10.0.18362.0. Similar issues are:
https://github.com/urho3d/Urho3D/issues/2545
https://developercommunity.visualstudio.com/content/problem/739697/c2118-error-with-windows-kits-100183620-in-winnth.html
Updating to SDL 2.0.10 seems to fix it.

I've manually re-applied all the patches to the SDL CMakeLists.txt in the sdl directory in the SDK, made a patch to replace the existing SDL CMakeLists.txt patches, which [applies in the TravisCI test build](https://travis-ci.org/github/freeorion/freeorion-sdk/jobs/741865938#L5348) and locally for me. After that, the Windows build seems fine, but [the OSX TravisCI build fails](https://travis-ci.org/github/freeorion/freeorion-sdk/jobs/741865938#L5728). The SDK TravisCI builds successfully without any patches applied, though, as in this pull request.

@Vezza can you build the SDK with this SDL version and without patches applied?

@o01eg or @adrianbroher any concerns with omitting those patches until someone who knows CMake better can fix it?

### CODE REVIEW

**Comment by o01eg** [comment]
If you can build FreeOrion with SDK without those patches I think it's fine.

**Comment by geoffthemedio** [comment]
> If you can build FreeOrion with SDK without those patches I think it's fine.

Several of them are OSX / APPLE specific.

I also end up with an extra `SDL2main.lib` that isn't in the master SDK build.

**Comment by Vezzra** [comment]
> Several of them are OSX / APPLE specific, so need some feedback from Vezzra, I think.

Sorry, didn't get around to it yet. My vacation turned out not to be much of a vacation, after several of my co-workers at the office caught COVID-19 I had to help out. What time I could spare for FO I used for trying to get freeorion/freeorion#3205 working with my prototype.

I've got this PR on my list, but it will take my some time until I can take a look at it.

**Comment by Vezzra** [comment]
Ok, got around to try building the SDK on macOS using this PR. The process fails when trying to build the Boost library, I'm getting this error I have no idea how to fix:
```
error: "10.9" is not a known value of feature <macosx-version-min>
error: legal values:
```
I remember having had issues with that option back when we still built the SDKs manually. But I can't remembar what I did to get it working. Googling didn't yield any useful results unfortunately...

**Comment by o01eg** [comment]
@Vezzra I suppose it is something related https://stackoverflow.com/questions/15738792/should-boost-bjam-b2-fail-when-darwin-jams-macosx-version-min-is-set-to-a-sdk-v

**Comment by Vezzra** [comment]
@o01eg, well, maybe, anything is possible, but that question is *over 7 years old* - that can't be still the same issue?!?!

And not having the SDK for the min deployment version installed shouldn't be an issue. After all, it doesn't tell which SDK to build/link against, but on what macOS versions the final app should be able to run.

Anyway, if this is really still this same issue, how to fix it? I don't really know how to fiddle with Boost's build system...

**Comment by Vezzra** [comment]
All that said, this isn't an issue of this PR. I just checked, I also can't build the latest version of the SDK on my system. Same error.

No idea what's wrong here. And until I can figure that out, I can't really help with this PR, sorry...

**Comment by geoffthemedio** [comment]
I suppose you could disable building Boost in order to let the build go longer to reach SDL... Or can the list of sources be reordered?

**Comment by o01eg** [comment]
@Vezzra Looks like it help https://travis-ci.org/github/o01eg/freeorion-sdk/jobs/744016639

Question was about MacOS 10.8 and we got issue with 10.9 I suppose time isn't big matter here.

**Comment by o01eg** [comment]
On windows it fails with `freetype` cannot find `libpng`.

**Comment by geoffthemedio** [comment]
> On windows it fails with `freetype` cannot find `libpng`.

What do you mean / how do you get this result? I just built the SDK with this pull request applied on Windows 10 with MSVC 2017 without problems.

**Comment by o01eg** [comment]
@geoffthemedio I got it here https://travis-ci.org/github/o01eg/freeorion-sdk/builds/744016638 when I tried to solve MacOSX issue.

**Comment by geoffthemedio** [comment]
Has the Travis Windows build ever worked?

Even if it did, that appears to be a separate issue. I want it to at least work to build the SDK locally, which I can with this pull request applied.

**Comment by o01eg** [comment]
@geoffthemedio 

> Has the Travis Windows build ever worked?

Maybe we should return back to Appveyor due Travis CI news.

**Comment by geoffthemedio** [comment]
Possibly, but that's a separate issue.

**Comment by o01eg** [comment]
@Vezzra  Could you check if https://github.com/o01eg/freeorion-sdk/commit/a43eee601654e530a82fe1486f5fbbe9a03013af fixes issue for you on MacOS?

**Comment by Vezzra** [comment]
@o01eg, yes, with that commit I can build the SDK.

However, the SDL framework library does not get packaged correctly in the SDK, so trying to build FO with that SDK gives me these errors already when cmake tries to configure the build:
```
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find SDL (missing: SDL_LIBRARY SDL_INCLUDE_DIR)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSDL.cmake:117 (find_package_handle_standard_args)
  CMakeLists.txt:253 (find_package)
```
Looking into the SDK reveals that instead of having a proper SDL2 framwork folder structure in the "Frameworks" dir, I got extra "bin", "lib" and "include" folders containing the various bits and pieces of the SDL framework.

So, progress made, but we are not there yet.

**Comment by o01eg** [comment]
I suppose deleted patches/sdl/0004-CMake-Add-MacOSX-Framework-support.patch did framework part.

**Comment by Vezzra** [comment]
> I suppose deleted patches/sdl/0004-CMake-Add-MacOSX-Framework-support.patch did framework part.

Most likely...

**Comment by geoffthemedio** [comment]
I can try again to create a version of the patch updated for the new SDL version. It was frequently refusing to apply when running the script even when it worked fine for me applying it manually, though.

**Comment by o01eg** [comment]
@Vezzra Try with it https://github.com/o01eg/freeorion-sdk/commit/8e8941abfe1f8a453d89c4e37e7f83dd0a27a180

**Comment by o01eg** [comment]
Restored all patches https://github.com/o01eg/freeorion-sdk/commit/aef2039877c593672e3b3d530cc87755d319d79e

**Comment by geoffthemedio** [comment]
> Restored all patches [o01eg@aef2039](https://github.com/o01eg/freeorion-sdk/commit/aef2039877c593672e3b3d530cc87755d319d79e)

Seems to work for me. When I tried myself it would refuse to apply the hunks, but it likes your version.

**Comment by o01eg** [comment]
It's failing on CI although https://travis-ci.org/github/o01eg/freeorion-sdk/jobs/744207132

**Comment by Vezzra** [comment]
> @Vezzra Try with it o01eg@8e8941a

Will try to get to that tomorrow.

**Comment by o01eg** [comment]
> Will try to get to that tomorrow.

@Vezzra I fixed CI: https://travis-ci.org/github/o01eg/freeorion-sdk/jobs/744244644

There is commit https://github.com/o01eg/freeorion-sdk/commit/107002c41b068af938175674d9d1953e196a094c

**Comment by geoffthemedio** [comment]
Can you make your own pull request then?

**Comment by o01eg** [comment]
Yes, I forgot about #56

**Pull request closed without merging**
