### PR TITLE
Bump boost version to 1.79.0

### LINKED ISSUE #92: Bump Boost Version
When buliding FreeOrion in MSVC with the Boost version currently in the SDK, there are a bunch of warnings like
`**include\boost\function_output_iterator.hpp(14): message : This header is deprecated. Use <boost/iterator/function_output_iterator.hpp> instead.**` throughout the build log. These seem to come from within Boost code, not anything FreeOrion or the SDK are doing.

I assume that bumping the Boost version a bit would resolve this.

### PR DESCRIPTION
**Pull request by o01eg**
Fixes #92

### CODE REVIEW

**Review by Vezzra — DISMISSED** [review]
Fails to buils on macOS. Got this error:
```
[ 32%] Performing patch step for 'boost'
patching file boost/log/detail/setup_config.hpp
patching file tools/build/src/tools/package.jam
Hunk #1 succeeded at 234 (offset 135 lines).
patching file tools/build/src/tools/darwin.jam
Hunk #2 FAILED at 204.
```

**Review by Vezzra — APPROVED** [review]
SDK builds successfully with this PR on macOS.

FO also builds and runs successfully using that SDK. The error @geoffthemedio encountered on Windows does not turn up on macOS.

**Comment by o01eg** [comment]
@geoffthemedio I see you added workaround to FreeOrion master, does it works for you also so I can merge it?

**Comment by geoffthemedio** [comment]
> @geoffthemedio I see you added workaround to FreeOrion master, does it works for you also so I can merge it?

yes

**Pull request merged**
