### PR TITLE
Update boost to 1.83

### PR DESCRIPTION
**Pull request by geoffthemedio**
...

### CODE REVIEW

**Comment by geoffthemedio** [comment]
@Vezzra could you check if this SDK version works for you for building FreeOrion?

**Comment by Vezzra** [comment]
> @Vezzra could you check if this SDK version works for you for building FreeOrion?

It does. FO builds and runs with an SDK based on this PR on Mac.

**Comment by geoffthemedio** [comment]
@o01eg any concerns?

**Comment by o01eg** [comment]
No, it looks fine.

**Pull request merged**
