### PR TITLE
Update boost and python-cmake

### PR DESCRIPTION
**Pull request by o01eg**
Extracted from #48.

Updates boost to 1.69, next version update is in #50.

Should be usable even with python2 only support.

### CODE REVIEW

**Comment by o01eg** [comment]
@adrianbroher I've updated boost to 1.68 and changed some gil patches, could you review it?

**Comment by o01eg** [comment]
It looks like boost >= 1.67 requires to add `bcrypt.lib` on windows https://github.com/boostorg/uuid/issues/68

**Comment by o01eg** [comment]
Next thing I catch is https://github.com/boostorg/python/issues/212

**Comment by o01eg** [comment]
There is a bug in python's `pyerror.h` redefines `snprinf` after upgrading boost to 1.69

https://bugs.python.org/issue36020
https://github.com/nlohmann/json/issues/1408

**Comment by o01eg** [comment]
I've fixed `pyerror.h` in generated SDK and freeorion builds and runs, but I suppose patches to python should be applied with `python-cmake`.

**Comment by o01eg** [comment]
I've prepared patch for `python-cmake` but it failed for apply on python with windows EOL. If I converts it to unix EOL it failed to apply on python-cmake.

**Comment by o01eg** [comment]
I've updated boost to 1.70 but found errors about missing gil files `boost/gil/gil_config.hpp` and `boost/gil/extension/io/io_error.hpp`. Could someone help with it?

**Comment by o01eg** [comment]
I've split out boost 1.69 to 1.70 so it possible to merge this PR now.

**Comment by geoffthemedio** [comment]
> I've split out boost 1.69 to 1.70 so it possible to merge this PR now.

But pull request 50 is listed as superseding this. Which should be merged?

**Comment by o01eg** [comment]
> But pull request 50 is listed as superseding this. Which should be merged?

#50 still has unsolved issues so only this PR could be merged.

**Pull request merged**
