### PR TITLE
Install boost-timer dependency into Docker image

### PR DESCRIPTION
**Pull request by adrianbroher**

### CODE REVIEW

**Comment by adrianbroher** [comment]
@geoffthemedio ping

**Comment by Vezzra** [comment]
@adrianbroher, I assume you only need someone to merge this, correct?

**Comment by adrianbroher** [comment]
Yes, but Geoff can do it by himself, as he is the person who needed it in the first place.

**Comment by geoffthemedio** [comment]
Debating whether to do this or adapt ScopedTimer.

**Comment by adrianbroher** [comment]
@geoffthemedio Assuming you are now using the ScopedTimer and friends this PR is not needed anymore, right?

**Comment by geoffthemedio** [comment]
right

**Comment by o01eg** [comment]
Does `boost-timer` have some improvements over current implementation? Maybe we should add it to SDK and then move to use it?

**Comment by geoffthemedio** [comment]
I'm not aware of any advantage `boost::timer` has of the existing `ScopedTimer` implementation.

**Pull request closed without merging**
