### PR TITLE
Update Python CMake scripts

### PR DESCRIPTION
**Pull request by o01eg**
Somehow newer python version cause CI to fail so I split out python-cmake-buildsystem upgrade separately to check if error related to build system or python.

### CODE REVIEW

**Comment by o01eg** [comment]
Would be nice to test it separately from CI, because, as I see, Python 3.9.10 build on your PC but not in Github Actions. Also MacOS Github Actions doesn't yet work.

**Comment by geoffthemedio** [comment]
No idea why, but building this branch with default settings for the first `cmake` call succeeds, but the resulting SDK gives me ~16k linker errors for various non-Python stuff when building FreeOrion

[sdk_build.log](https://github.com/freeorion/freeorion-sdk/files/8727749/sdk_build.log)

Will try again specifying more stuff...

**Comment by o01eg** [comment]
@geoffthemedio SDK was built without `-A` parameter?

**Comment by o01eg** [comment]
Merged in #95

**Pull request closed without merging**
