### PR TITLE
Update Boost to 1.86.0

### PR DESCRIPTION
**Pull request by o01eg**

### CODE REVIEW

**Comment by o01eg** [comment]
Test build https://github.com/o01eg/freeorion/actions/runs/12524727395/job/34935554127

Windows CMake projects passed but MSVS projects failed to build:

```
   SerializeEmpire.cpp
  SerializeModeratorAction.cpp
  SerializeMultiplayerCommon.cpp
    CL!InvokeCompilerPassW()+0x8267f
  INTERNAL COMPILER ERROR in 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.42.34433\bin\HostX86\x86\CL.exe'
      Please choose the Technical Support command on the Visual C++
      Help menu, or open the Technical Support help file for more information
cl : command line  error D8040: error creating or communicating with child process [D:\a\freeorion\freeorion\msvc2022\Common\Common.vcxproj]
```

**Comment by geoffthemedio** [comment]
Building the SDK, I'm getting a huge spam of stuff like this output to the console, for several minutes at least now...
````
     copy /b "C:\Users\g_top\Desktop\FOSDK16\sdkbuild\build186\boost-prefix\src\boost\boost\test\minimal
  .hpp" + this-file-does-not-exist-A698EE7806899E69 "C:\Users\g_top\Desktop\FOSDK16\sdkbuild\build186\INS
  TALL\include\boost\test\minimal.hpp"

  C:\Users\g_top\Desktop\FOSDK16\sdkbuild\build186\boost-prefix\src\boost\boost\test\minimal.hpp
          1 file(s) copied.
  common.copy C:\Users\g_top\Desktop\FOSDK16\sdkbuild\build186\INSTALL\include\boost\test\output_test_str
  eam.hpp
````

**Comment by o01eg** [comment]
Yes, I've enabled `-d 2` debug output to try to find issue and didn't disable it back.

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/commit/1c90867c78561ed6ffd8d6b733b589f844365a2d prevents the internal compiler error

**Review by Vezzra — APPROVED** [review]
Works

**Pull request merged**
