### PR TITLE
Fix OSX bootstrapper not moving .travis.yml file

### PR DESCRIPTION
**Pull request by Vezzra**

### CODE REVIEW

**Comment by adrianbroher** [comment]
What's the point of this PR?

**Comment by adrianbroher** [comment]
Never mind, I read the comment in the other PR.

**Comment by Vezzra** [comment]
Oh, ok. Sorry, I could have added the explanation here too.

**Comment by adrianbroher** [comment]
I took a different approach as the suggested PR.  Your solution requires to update the bootstrap.command every time we add or remove dot-files or directories in the freeorion/freeorion repository.  Using `shopt -s dotglob` however matches all files including dot files and dirs without matching against `.` and `..`.

**Comment by Vezzra** [comment]
Excellent 👍

**Pull request closed without merging**
