### PR TITLE
Try to fix GLEW build

### PR DESCRIPTION
**Pull request by o01eg**
Should help with GLEW build issue #67 and https://github.com/freeorion/freeorion-sdk/pull/88#issuecomment-1127981977 but ensuring pass correct architecture value.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
No change as far as I can tell. `glew.lib` is still 740 KB and I get linker errors building GG.

SDK build log attached... GLEW stuff starts at line 1978 `Creating directories for 'glew'`...
[sdk_master_build.txt](https://github.com/freeorion/freeorion-sdk/files/8708340/sdk_master_build.txt)

**Comment by o01eg** [comment]
FreeType chooses compiler:

```
  Performing configure step for 'freetype'
  CMake Deprecation Warning at CMakeLists.txt:78 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.
  
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  
  
  -- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19043.
  -- The C compiler identification is MSVC 19.29.30137.0
  -- The CXX compiler identification is MSVC 19.29.30137.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x86/cl.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x86/cl.exe - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done

```

GLEW chooses compiler:
```
  Performing configure step for 'glew'
  -- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19043.
  -- The C compiler identification is MSVC 19.29.30137.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
```

**Comment by o01eg** [comment]
Could you upload entire `CMakeCache.txt`?

**Comment by o01eg** [comment]
Toolset and platform aren't passed.

```
//Name of generator.
CMAKE_GENERATOR:INTERNAL=Visual Studio 16 2019
//Generator instance identifier.
CMAKE_GENERATOR_INSTANCE:INTERNAL=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community
//Name of generator platform.
CMAKE_GENERATOR_PLATFORM:INTERNAL=
//Name of generator toolset.
CMAKE_GENERATOR_TOOLSET:INTERNAL=
```
```
//Name of generator.
CMAKE_GENERATOR:INTERNAL=Visual Studio 16 2019
//Generator instance identifier.
CMAKE_GENERATOR_INSTANCE:INTERNAL=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community
//Name of generator platform.
CMAKE_GENERATOR_PLATFORM:INTERNAL=Win32
//Name of generator toolset.
CMAKE_GENERATOR_TOOLSET:INTERNAL=v142
```

Does it have some verbosity settings?

**Comment by o01eg** [comment]
I also add commit to set those values differently

**Comment by geoffthemedio** [comment]
> Does it have some verbosity settings?

Not sure what "it" is.

**Comment by geoffthemedio** [comment]
No change in `glew.lib` size or GG link errors.

**Comment by geoffthemedio** [comment]
...
[CMakeCache.txt](https://github.com/freeorion/freeorion-sdk/files/8710147/CMakeCache.txt)
[CMakeCache.txt](https://github.com/freeorion/freeorion-sdk/files/8710150/CMakeCache.txt)

**Comment by o01eg** [comment]
Raised minimum CMake version to 3.7 and use `SOURCE_SUBDIR` option for CMake external project. As I seen in build logs it correctly choose compiler https://github.com/o01eg/freeorion-sdk/runs/6485341097?check_suite_focus=true

**Comment by o01eg** [comment]
@Vezzra Does MacOS have CMake 3.7?

**Comment by geoffthemedio** [comment]
Looks like CMake 3.7 was released near the end of 2018.

**Comment by geoffthemedio** [comment]
I maybe wasn't actually using the modified versions you were uploading... I did the clone using the URL from the "Code" drop-button at the top of the page for the branch, but I think that default to your master branch, not the modified branch for the pull request. So possibly one of the earlier fixes could have worked?

**Comment by o01eg** [comment]
I suppose latest solution with `SOURCE_SUBDIR` is cleaner

**Comment by o01eg** [comment]
Correct compiler now:

```
2022-05-18T12:09:40.6785810Z   Performing configure step for 'glew'
2022-05-18T12:09:41.9943305Z   -- The C compiler identification is MSVC 19.16.27048.0
2022-05-18T12:09:42.0269121Z   -- Detecting C compiler ABI info
2022-05-18T12:09:42.9053504Z   -- Detecting C compiler ABI info - done
2022-05-18T12:09:42.9076628Z   -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.16.27023/bin/HostX64/x86/cl.exe - skipped
```

**Comment by geoffthemedio** [comment]
FreeOrion builds also work.

**Comment by o01eg** [comment]
Oh, FreeOrion itself requires CMake 3.8 so I suppose MacOS definitely build this SDK too.

**Comment by Vezzra** [comment]
@o01eg

> Does MacOS have CMake 3.7?

```
$ cmake --version
cmake version 3.14.5
```
Yes 😃

**Pull request merged**
