### PR TITLE
Drop python2 support

### PR DESCRIPTION
**Pull request by o01eg**

### CODE REVIEW

**Comment by o01eg** [comment]
I prefer it to be postponed after `v11` SDK release.

**Comment by geoffthemedio** [comment]
> I prefer it to be postponed after `v11` SDK release.

Probably reasonable for a transition release to support the old version as well.

**Comment by o01eg** [comment]
@geoffthemedio Could `v11` be released now? I think it better to release `v12` soon if something will be required like it was in `v9-v10`, and `v6-v7`.

**Comment by geoffthemedio** [comment]
I don't object, but @adrianbroher seemed to have some reason to delay, though I don't know what it would be. If he doesn't comment by tomorrow, then I'd say go ahead anyway...

**Comment by Vezzra** [comment]
> I prefer it to be postponed after v11 SDK release.

Agreed.

**Pull request merged**
