### PR TITLE
Add MSVS 2019 support to Travis CI

### PR DESCRIPTION
**Pull request by o01eg**
Add support to build SDK for MSVS 2019.

### CODE REVIEW

**Comment by o01eg** [comment]
It builds now

**Comment by geoffthemedio** [comment]
OK, I suppose.

When I try to build FreeOrion itself with the v142 toolset SDK, I get link errors in GLEW. I guess having the options / flexible setup in the SDK scripts is fine, though...

**Comment by geoffthemedio** [comment]
this is probably redundant now?

**Comment by o01eg** [comment]
@geoffthemedio yes

**Pull request closed without merging**
