### PR TITLE
Update boost to 1.82.0

### PR DESCRIPTION
**Pull request by o01eg**
Not urgent but if it works without issues could be made into upcoming release.

### CODE REVIEW

**Review by Vezzra — APPROVED** [review]
Works on Mac. Can build the SDK, and build and run current master with that SDK.

**Comment by geoffthemedio** [comment]
````
-- Boost version: 1.82.0
-- Found the following Boost libraries:
--   unit_test_framework
CMake Error at CMakeLists.txt:371 (message):
  FreeOrion version failed

-- Configuring incomplete, errors occurred!
````
[CMakeOutput.log](https://github.com/freeorion/freeorion-sdk/files/11259931/CMakeOutput.log)
[CMakeError.log](https://github.com/freeorion/freeorion-sdk/files/11259932/CMakeError.log)

**Comment by o01eg** [comment]
@geoffthemedio More looks like python issue. Was executable found correctly?

**Comment by geoffthemedio** [comment]
````
-- Found PythonInterp: C:/Users/g_top/Desktop/FOSDK15/bin/python3.9.exe (Required is at least version "3.7")
-- Found PythonLibs: C:/Users/g_top/Desktop/FOSDK15/lib/python39.lib (Required is at least version "3.7")
-- Python library version detected
````

````
CMake Error at cmake/FindBoost.cmake:2174 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.82.0

  Boost include path: C:/Users/g_top/Desktop/SDK15/include

  Could not find the following Boost libraries:

          boost_python
````

**Comment by o01eg** [comment]
What "Boost python version " does it detect?

**Comment by o01eg** [comment]
Does `PYTHONLIBS_VERSION_STRING` variable get empty? Is it clean run or maybe other python got cached?

**Comment by o01eg** [comment]
@geoffthemedio Do MS VS project works? CMake could be tuned if needed later.

**Comment by geoffthemedio** [comment]
> @geoffthemedio Do MS VS project works? CMake could be tuned if needed later.

Didn't try it before I had to go get on a train.

**Comment by o01eg** [comment]
Made release with it https://github.com/o01eg/freeorion-sdk/releases/tag/v17

**Pull request merged**
